<?php

/**
 * @file
 * Contains aa_pages.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aa_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aa_pages module.
    case 'help.page.aa_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implementations related to Air Assist pages.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function aa_pages_theme() {
  return [
    'about_us' => [
      'variables' => [
        'about_us_node' => NULL,
        'social_links' => NULL,
      ],
    ],
    'testimonials' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'slider' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'contact_form' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aa_pages_form_entity_subqueue_slider_edit_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  $form['actions']['submit']['#submit'][] = 'aa_pages_slider_subqueue_form_submit';
}

function aa_pages_slider_subqueue_form_submit(&$form, FormStateInterface $formState) {
  /** @var \Drupal\Core\Cache\CacheTagsInvalidatorInterface $service */
  $service = \Drupal::service('cache_tags.invalidator');
  $service->invalidateTags(['slider']);
}
