<?php

/**
 * @file
 * Contains hook implementations.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function aa_user_theme($existing, $type, $theme, $path) {
  return [
    'join_us' => [
      'variables' => [
        'login_form' => NULL,
        'register_form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aa_user_form_user_register_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  $form['actions']['submit']['#submit'][] = 'aa_user_register_submit';
}

function aa_user_register_submit(array $form, FormStateInterface $form_state) {
  $form_state->setRedirect('aa_user.join_us_controller_build');
}
