<?php

/**
 * @file
 * Contains aa_refund.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aa_refund_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aa_refund module.
    case 'help.page.aa_refund':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Functionalities related to the refunds.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function aa_refund_theme() {
  return [
    'refund_reason' => [
      'variables' => [
        'items' => NULL,
      ],
    ],
    'refund_steps' => [
      'variables' => [
        'items' => NULL,
        'titles' => NULL,
      ],
    ],
    'refund_register' => [
      'variables' => [
        'register' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aa_refund_form_entity_subqueue_refund_reason_edit_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  /** @var \Drupal\Core\Cache\CacheTagsInvalidatorInterface $service */
  $service = \Drupal::service('cache_tags.invalidator');
  $service->invalidateTags(['refund']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aa_refund_form_user_register_form_alter(
  &$form,
  \Drupal\Core\Form\FormStateInterface $form_state,
  $form_id
) {
  $form['actions']['submit']['#submit'][] = 'aa_refund_submit';
}

function aa_refund_submit(&$form,
  \Drupal\Core\Form\FormStateInterface $form_state) {

  $values = $form_state->cleanValues()->getValues();
  $uid = $values['uid'];
  $eligibility = unserialize($_SESSION['eligibility']);

  $storage = \Drupal::entityTypeManager()->getStorage('refund_application');

  $entity = $storage->create([
    'user_id' => $uid,
    'name' => 'Test ' . $uid,
    'refund_submission_data' => $_SESSION['eligibility'],
    'type' => 'test',
  ]);

  $entity->save();
  drupal_set_message('Your refund application has been submitted. Please follow the instructions to log in to your account.');
}